services:
  strava-ai:
    build:
      dockerfile: dockerfile
    container_name: strava-ai
    restart: unless-stopped
    ports:
      - 3400:3400
    volumes:
      - /tmp/stravai:/config
      - ./assets:/assets
      - /etc/localtime:/etc/localtime:ro
    environment:
      - STRAVA_CLIENT_ID="${STRAVA_CLIENT_ID:-}"
      - STRAVA_CLIENT_SECRET="${STRAVA_CLIENT_SECRET:-}"
      - OLLAMA_URL="${OLLAMA_URL:-}"
      - STRAVA_INTERVAL="${STRAVA_INTERVAL:-}"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - /ollama/root:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 16G
  pull-ollama-model:
    image: ollama/ollama:latest
    container_name: pull-ollama-model
    volumes:
      - /ollama/root:/root/.ollama
    entrypoint: /bin/sh -c "ollama serve & sleep 5 && ollama pull llama3.2"
    depends_on:
      - ollama
